### ISSUE TITLE
Address config mismatch in README

### ISSUE THREAD

**Issue by ConnectedSystems** [ConnectedSystems/GBR-Bathy10m#11]
The readme states that a config (TOML) file is needed with:

```TOML
[aca_data]
ALLEN_ATLAS_DIR = "path to Allen Atlas data"  # location of Allen Atlas datasets

[wave_data]
WAVE_DATA_DIR = "path to wave data" # location of wave dataset
```

however the code (in `common.jl`) looks for:

ACA_DATA_DIR

There may be other discrepancies.
